# require 'net/http'
# require 'open-uri'
# require 'json'
require 'pry'
require 'colorize'
require 'colorized_string'
require 'httparty'

require_relative '../lib/cli'
require_relative '../lib/pokemon'
require_relative '../lib/api'
